server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "Access-Control-Allow-Headers, Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
            allowedMethods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
  
      routes:
        - id: peliculas-server
          uri: lb://peliculas-server
          predicates:
            - Path=/peliculas/**


        - id: catalogos-server
          uri: lb://catalogos-server
          predicates:
            - Path=/catalogos/** 
